# Generated by Django 2.0 on 2018-08-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descip',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pub',
            new_name='pub_date',
        ),
    ]
