# Generated by Django 2.0 on 2019-03-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_auto_20180926_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsn', models.CharField(max_length=10000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.College')),
            ],
        ),
    ]
