# Generated by Django 2.0 on 2019-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0008_industryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='academic_rate',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='infra_rate',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='placement_rate',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Other', max_length=20),
        ),
    ]
