# Generated by Django 2.0 on 2019-04-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_auto_20190309_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='nirf_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='pic',
            field=models.ImageField(default='def.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='academic_rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default='Other'),
        ),
        migrations.AlterField(
            model_name='review',
            name='infra_rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default='Other'),
        ),
        migrations.AlterField(
            model_name='review',
            name='placement_rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default='Other'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.College'),
        ),
        migrations.AddField(
            model_name='review',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reviews.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reviews.Department'),
            preserve_default=False,
        ),
    ]
