# Generated by Django 2.0 on 2019-04-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0010_auto_20190401_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.Category')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.College')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.Department')),
            ],
        ),
    ]
