# Generated by Django 2.0 on 2019-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0012_studentuser_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
